### ISSUE TITLE
windows 域账号调用该插件后，没有收到邮件

### ISSUE THREAD

**Issue by xujh0225** [TencentBlueKing/ci-sendEmail#19]
流程调用sendEmail插件，通知的用户为域用户，并设置了邮箱，但实际没有收到邮件。
![7](https://user-images.githubusercontent.com/18331663/109461841-b2041c00-7a9d-11eb-87e8-e125dba381d2.jpg)
![8](https://user-images.githubusercontent.com/18331663/109461854-b7f9fd00-7a9d-11eb-97cb-e68cc2cd7af1.jpg)

**Comment by irwinsun** [comment]
这个和插件无关，应该要看对应的蓝鲸平台发邮件是否支持域帐号
